"""
install.py: Installation of OpenCore files to ESP
"""

import logging
import plistlib
import subprocess
import re

from pathlib import Path

from . import utilities, subprocess_wrapper
from .efi_transaction import EFIBootloaderTransaction
from .operation_lock import execute_locked_root_operation

from .. import constants


class tui_disk_installation:
    def __init__(self, versions):
        self.constants: constants.Constants = versions

    def list_disks(self):
        all_disks = {}
        # TODO: AllDisksAndPartitions is not supported in Snow Leopard and older
        try:
            # High Sierra and newer
            disks = plistlib.loads(subprocess.run(["/usr/sbin/diskutil", "list", "-plist", "physical"], stdout=subprocess.PIPE).stdout.decode().strip().encode())
        except ValueError:
            # Sierra and older
            disks = plistlib.loads(subprocess.run(["/usr/sbin/diskutil", "list", "-plist"], stdout=subprocess.PIPE).stdout.decode().strip().encode())
        for disk in disks["AllDisksAndPartitions"]:
            try:
                disk_info = plistlib.loads(subprocess.run(["/usr/sbin/diskutil", "info", "-plist", disk["DeviceIdentifier"]], stdout=subprocess.PIPE).stdout.decode().strip().encode())
            except:
                # Chinesium USB can have garbage data in MediaName
                diskutil_output = subprocess.run(["/usr/sbin/diskutil", "info", "-plist", disk["DeviceIdentifier"]], stdout=subprocess.PIPE).stdout.decode().strip()
                ungarbafied_output = re.sub(r'(<key>MediaName</key>\s*<string>).*?(</string>)', r'\1\2', diskutil_output).encode()
                disk_info = plistlib.loads(ungarbafied_output)
            try:
                all_disks[disk["DeviceIdentifier"]] = {"identifier": disk_info["DeviceNode"], "name": disk_info.get("MediaName", "Disk"), "size": disk_info["TotalSize"], "partitions": {}}
                for partition in disk["Partitions"]:
                    partition_info = plistlib.loads(subprocess.run(["/usr/sbin/diskutil", "info", "-plist", partition["DeviceIdentifier"]], stdout=subprocess.PIPE).stdout.decode().strip().encode())
                    all_disks[disk["DeviceIdentifier"]]["partitions"][partition["DeviceIdentifier"]] = {
                        "fs": partition_info.get("FilesystemType", partition_info["Content"]),
                        "type": partition_info["Content"],
                        "name": partition_info.get("VolumeName", ""),
                        "size": partition_info["TotalSize"],
                    }
            except KeyError:
                # Avoid crashing with CDs installed
                continue

        supported_disks = {}
        for disk in all_disks:
            if not any(all_disks[disk]["partitions"][partition]["fs"] in ("msdos", "EFI") for partition in all_disks[disk]["partitions"]):
                continue
            supported_disks.update({
                disk: {
                    "disk": disk,
                    "name": all_disks[disk]["name"],
                    "size": utilities.human_fmt(all_disks[disk]['size']),
                    "partitions": all_disks[disk]["partitions"]
                }
            })
        return supported_disks

    def list_partitions(self, disk_response, supported_disks):
        # Takes disk UUID as well as diskutil dataset generated by list_disks
        # Returns list of FAT32 partitions
        disk_identifier = disk_response
        selected_disk = supported_disks[disk_identifier]

        supported_partitions = {}

        for partition in selected_disk["partitions"]:
            if selected_disk["partitions"][partition]["fs"] not in ("msdos", "EFI"):
                continue
            supported_partitions.update({
                partition: {
                    "partition": partition,
                    "name": selected_disk["partitions"][partition]["name"],
                    "size": utilities.human_fmt(selected_disk["partitions"][partition]["size"])
                }
            })
        return supported_partitions


    def _determine_sd_card(self, media_name: str):
        # Array filled with common SD Card names
        # Note most USB-based SD Card readers generally report as "Storage Device"
        # Thus no reliable way to detect further without parsing IOService output (kUSBProductString)
        if any(x in media_name for x in ("SD Card", "SD/MMC", "SDXC Reader", "SD Reader", "Card Reader")):
            return True
        return False


    def _disk_info(self, identifier: str) -> dict:
        result = subprocess.run(["/usr/sbin/diskutil", "info", "-plist", identifier], capture_output=True)
        if result.returncode != 0:
            raise RuntimeError(f"Cannot query disk identity: {identifier}")
        info = plistlib.loads(result.stdout)
        if not isinstance(info, dict):
            raise ValueError("Invalid disk identity response")
        return info


    def install_opencore(self, full_disk_identifier: str) -> bool:
        if not isinstance(full_disk_identifier, str) or not re.fullmatch(r"disk\d+s\d+", full_disk_identifier):
            logging.error("Invalid EFI partition identifier")
            return False

        return execute_locked_root_operation(lambda: self._install_opencore_locked(full_disk_identifier))


    def _install_opencore_locked(self, full_disk_identifier: str) -> bool:

        owns_mount = False
        success = False
        identity = None
        try:
            before = self._disk_info(full_disk_identifier)
            identity = before.get("DiskUUID") or before.get("VolumeUUID")
            if before.get("DeviceIdentifier") != full_disk_identifier or not isinstance(identity, str) or not identity:
                raise ValueError("EFI partition identity cannot be established")
            if before.get("Content") != "EFI" and before.get("FilesystemType") != "msdos":
                raise ValueError("Selected partition is not an EFI or FAT partition")
            if before.get("Mounted") is not True:
                logging.info(f"Mounting partition: {full_disk_identifier}")
                result = subprocess_wrapper.run_as_root(
                    ["/usr/sbin/diskutil", "mount", full_disk_identifier], capture_output=True,
                )
                if result.returncode != 0:
                    subprocess_wrapper.log(result)
                    return False
                owns_mount = True

            mounted = self._disk_info(full_disk_identifier)
            if mounted.get("DeviceIdentifier") != full_disk_identifier or (mounted.get("DiskUUID") or mounted.get("VolumeUUID")) != identity:
                raise ValueError("Selected EFI partition changed while mounting")
            mount_point = mounted.get("MountPoint")
            if mounted.get("Mounted") is not True or not isinstance(mount_point, str) or not Path(mount_point).is_absolute():
                raise ValueError("EFI partition did not mount")
            mount_path = Path(mount_point)
            success = EFIBootloaderTransaction(
                self.constants.opencore_release_folder, mount_path, self.constants.boot_efi,
            ).install()
            if success:
                # An icon is cosmetic; its failure cannot invalidate verified boot files.
                try:
                    drive = self._disk_info(mounted["ParentWholeDisk"])
                    if self._determine_sd_card(drive.get("MediaName", "Disk")):
                        icon = self.constants.icon_path_sd
                    elif drive.get("SolidState") is True:
                        icon = self.constants.icon_path_ssd
                    elif mounted.get("BusProtocol") == "USB":
                        icon = self.constants.icon_path_external
                    else:
                        icon = self.constants.icon_path_internal
                    subprocess_wrapper.run_as_root_and_verify(
                        ["/bin/cp", str(icon), str(mount_path)], capture_output=True,
                    )
                except Exception as error:
                    logging.warning(f"OpenCore was installed, but the drive icon could not be updated: {error}")
        except Exception as error:
            logging.error(f"OpenCore installation failed: {error}")
            success = False
        finally:
            if owns_mount:
                try:
                    current = self._disk_info(full_disk_identifier)
                    if (current.get("DiskUUID") or current.get("VolumeUUID")) != identity:
                        raise ValueError("EFI identity changed; refusing to unmount another volume")
                    subprocess_wrapper.run_as_root_and_verify(
                        ["/usr/sbin/diskutil", "umount", full_disk_identifier], capture_output=True,
                    )
                except Exception as error:
                    logging.error(f"Unable to release EFI mount: {error}")
                    success = False

        if success:
            logging.info("OpenCore transfer complete")
        return success
